version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - "9292:9292"
    volumes:
      - .:/api
    environment:
      RACK_ENV: development

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./public:/docs
