# frozen_string_literal: true

require 'rspec/openapi'

RSpec::OpenAPI.path = 'public/openapi.yaml'
RSpec::OpenAPI.example_types = %i[request]

RSpec::OpenAPI.title = 'Fudo Challenge OpenAPI Documentation'
RSpec::OpenAPI.info = {
  description: 'Fudo Challenge API'
}

RSpec::OpenAPI.request_headers = %w[Authorization Content-Type]

RSpec::OpenAPI.response_headers = %w[x-powered-by]

# Set `servers` - generate servers of a schema file
RSpec::OpenAPI.servers = [{ url: 'http://localhost:9292' }]

# Set `security_schemes` - generate security schemes
RSpec::OpenAPI.security_schemes = {
  'Authorization' => {
    description: 'Authenticate API requests via a Token',
    type: 'apiKey',
    in: 'header',
    name: 'HTTP-AUTHORIZATION'
  }
}

RSpec::OpenAPI.comment = <<~EOS
  This file is auto-generated by rspec-openapi https://github.com/k0kubun/rspec-openapi

  When you write a spec in spec/requests, running the spec with `OPENAPI=1 rspec` will
  update this file automatically. You can also manually edit this file.
EOS
